services:
  ollama:
    image: "docker.io/ollama/ollama:latest"
    volumes:
      - ollama:/root/.ollama
    container_name: dictionary_ollama
    ports: 
      - 11434:11434
    networks:
      - back
    tty: true
    restart: unless-stopped

  postregres:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: postgres_db
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - back

  voc-app:
    build:
      context: .
    ports:
      - 3000:3000
    container_name: voc_app
    env_file: ".env"
    networks:
      - back
    develop:
      watch:
        - action: sync
          path: ./packages/Server
          target: /app
        - action: rebuild
          path: package.json

networks:
  back:
    driver: bridge
volumes:
  ollama: {}
  db: {}
